//
//  ASHPublicKey.h
//  ASHEBShop
//
//  Created by xmfish on 17/4/5.
//  Copyright © 2017年 ash. All rights reserved.
//

#import <Foundation/Foundation.h>
FOUNDATION_EXTERN NSString *kASH_EBSHOP_API_URL;
FOUNDATION_EXPORT NSString *kASH_NETWORK_SIGN;
FOUNDATION_EXPORT NSString *kASH_TAOBAO_PID;
FOUNDATION_EXPORT NSString *kASH_PRAISE_SAVE;
FOUNDATION_EXPORT NSString *kASH_CACHE_PATH;
FOUNDATION_EXPORT NSString *kASH_CART_CACHE_PATH;
FOUNDATION_EXPORT NSString *kASH_NO_CART_CACHE_PATH;
//post
FOUNDATION_EXPORT NSString *kASH_Post_Tab;
FOUNDATION_EXPORT NSString *kASHTaobaoQueryBagFinishNotification;
FOUNDATION_EXPORT NSString *kASHTaobaoQLoginSuccess;
//string
FOUNDATION_EXPORT NSString *kASH_NETWORK_Error;
